export default [
// "ziołowa polana mieszanka ziołowa",
// "babie lato mieszanka ziołowa",
// "złocisty poranek mieszanka ziołowa",
// "błogi spokój mieszanka ziołowa",
// "skupienie mieszanka ziołowa",
// "leśna ścieżka mieszanka ziołowa",
// "dobrej nocy mieszanka ziołowa",
// "wiśnia z beczki herbata",
// "piccolo herbata zielona z owocami",
"sencha herbata",
// "jagodowy pocałunek herbata owocowa",
"bai mu dan herbata biała",
"hibiskus herbata owocowa",
"radża chai oolong herbata",
"oolong herbata",
"rooibos w pasiece herbata z owocami",
"piracki rum herbata pu-erh z owocami",
"biała róża herbata biała",
"rooibos herbata",
"pu-erh herbata",
"chica herbata owocowa",
"kenia kangaita herbata czarna",
// "słodki sen herbata",
"el toro herbata czarna",
"golden monkey herbata czarna",
// "marchewkowe ciasto herbata",
// "lśniąca rosa herbata",
// "smoczy eliksir herbata",
// "jamajka herbata",
// "słoneczne tango herbata",
// "uczta wikinga herbata",
// "zimowy pałac herbata",
// "zorza polarna herbata",
// "quantico herbata",
// "belize herbata",
// "jabłkowe tornado herbata",
// "kodama herbata",
// "głębia pacyfiku herbata",
// "igraszka herbata",
// "równowaga herbata",
"pokrzywa liść",
"mniszek lekarski korzeń",
"podagrycznik ziele podagra",
"melisa lekarska",
"mięta pieprzowa liść",
"rumianek kwiat cały",
"nagietek kwiat",
"dziurawiec ziele promocja",
"szałwia lekarska liść",
"bez czarny kwiat",
"piołun ziele",
"lukrecja korzeń",
"czystek suszony polifenole borelioza",
"miodunka płucnik ziele",
"lawenda kwiat suszony",
"hibiskus kwiat",
"tymianek naturalny",
"brzoza liść",
"fiołek trójbarwny ziele",
"rumianek kwiat rozkrusz",
"macierzanka ziele",
"morwa biała liść",
"pokrzywa korzeń",
"jemioła pospolita",
"chmiel szyszka",
"mniszek lekarski ziele",
"rdest ptasi ziele promocja",
"serdecznik ziele",
"arcydzięgiel korzeń",
"jeżówka purpurowa ziele",
"mniszek lekarski kwiat",
// "czosnek niedźwiedzi",
"siemię lniane",
// "liść laurowy wawrzyn",
"zioła szwedzkie marii treben",
"malina liść",
"wrzos kwiat",
"lubczyk korzeń",
"sosna pączki",
"kocanka kwiat kocanki",
"bławatek chaber kwiat koszyczek",
"jagoda borówka czernica liść",
"czarna porzeczka liść",
"poziomka liść",
"jasnota kwiat + ziele",
"jeżyna liść",
"głóg kwiat",
"przytulia ziele przytulii",
"aronia owoc suszony",
];
